-- MySQL Script generated by MySQL Workbench
-- Mon Oct 13 14:02:50 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_review_movie
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_review_movie
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_review_movie` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_review_movie` ;

-- -----------------------------------------------------
-- Table `db_review_movie`.`cast`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_review_movie`.`cast` (
  `id_cast` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `age` VARCHAR(45) NULL DEFAULT NULL,
  `biodata` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_cast`),
  UNIQUE INDEX `id_cast_UNIQUE` (`id_cast` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `db_review_movie`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_review_movie`.`review` (
  `id_review` INT NOT NULL,
  `rating` VARCHAR(45) NULL DEFAULT NULL,
  `critics` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_review`),
  UNIQUE INDEX `id_review_UNIQUE` (`id_review` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_review_movie`.`movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_review_movie`.`movie` (
  `id_movie` INT NOT NULL,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  `summary` VARCHAR(45) NULL DEFAULT NULL,
  `year` VARCHAR(45) NULL DEFAULT NULL,
  `poster` VARCHAR(45) NULL DEFAULT NULL,
  `review_id_review` INT NOT NULL,
  `cast_id_cast` INT NOT NULL,
  PRIMARY KEY (`id_movie`),
  UNIQUE INDEX `id_movie_UNIQUE` (`id_movie` ASC) VISIBLE,
  INDEX `fk_movie_review1_idx` (`review_id_review` ASC) VISIBLE,
  INDEX `fk_movie_cast1_idx` (`cast_id_cast` ASC) VISIBLE,
  CONSTRAINT `fk_movie_review1`
    FOREIGN KEY (`review_id_review`)
    REFERENCES `db_review_movie`.`review` (`id_review`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movie_cast1`
    FOREIGN KEY (`cast_id_cast`)
    REFERENCES `db_review_movie`.`cast` (`id_cast`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_review_movie`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_review_movie`.`genre` (
  `id_genre` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `movie_id_movie` INT NOT NULL,
  PRIMARY KEY (`id_genre`),
  INDEX `fk_genre_movie1_idx` (`movie_id_movie` ASC) VISIBLE,
  CONSTRAINT `fk_genre_movie1`
    FOREIGN KEY (`movie_id_movie`)
    REFERENCES `db_review_movie`.`movie` (`id_movie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_review_movie`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_review_movie`.`profile` (
  `id_profile` INT NOT NULL,
  `age` VARCHAR(45) NULL DEFAULT NULL,
  `biodata` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_profile`),
  UNIQUE INDEX `id_profile_UNIQUE` (`id_profile` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_review_movie`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_review_movie`.`role` (
  `id_role` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `cast_id_cast` INT NOT NULL,
  PRIMARY KEY (`id_role`),
  UNIQUE INDEX `id_role_UNIQUE` (`id_role` ASC) VISIBLE,
  INDEX `fk_role_cast1_idx` (`cast_id_cast` ASC) VISIBLE,
  CONSTRAINT `fk_role_cast1`
    FOREIGN KEY (`cast_id_cast`)
    REFERENCES `db_review_movie`.`cast` (`id_cast`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_review_movie`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_review_movie`.`user` (
  `id_user` INT NOT NULL,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  `profile_id_profile` INT NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC) VISIBLE,
  INDEX `fk_user_profile_idx` (`profile_id_profile` ASC) VISIBLE,
  CONSTRAINT `fk_user_profile`
    FOREIGN KEY (`profile_id_profile`)
    REFERENCES `db_review_movie`.`profile` (`id_profile`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_review_movie`.`user_has_review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_review_movie`.`user_has_review` (
  `user_id_user` INT NOT NULL,
  `review_id_review` INT NOT NULL,
  PRIMARY KEY (`user_id_user`, `review_id_review`),
  INDEX `fk_user_has_review_review1_idx` (`review_id_review` ASC) VISIBLE,
  INDEX `fk_user_has_review_user1_idx` (`user_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_review_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `db_review_movie`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_review_review1`
    FOREIGN KEY (`review_id_review`)
    REFERENCES `db_review_movie`.`review` (`id_review`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
